# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cd33497f4aa3517c7fefdc0da8b9b797735b6e41259d890ec92ede9529e4eabea1313b5a7a32d299b296dca589b655bce5d25c88b5472edf7e7d2845481fb6c

test:
  secret_key_base: 5258f376ee011950efc405dc4a6ea6a37009dfb029845a4b3864c097d2ba5b2fee5f0b4f2b32c60217d3887251699c1ede38358870b84eba18ae1222f0d30afb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
